spring:
  application:
    name: flow
  profiles:
    active: secret
  datasource:
    url: ${H2_DB_URL}
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    stack:
      auto: false
    region:
      static: ${S3_REGION}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace