name: Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]

jobs:
  deploy: 
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PEM}}
          port: ${{secrets.PORT}}
          script: |
            echo "${{ secrets.USERNAME}}"
            ls 
            cd flow-subject
            echo "SUCCESS!!"
            git pull
            
