name: Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]

jobs:
  JDK:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'zulu'
      
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.PEM}}
          port: ${{secrets.PORT}}
          script: |
            if [ ! -d "flow-subject" ]; then
              git clone https://github.com/JongKookE/flow-subject
            fi
            cd flow-subject
            echo "SUCCESS!!"
            git pull
            chmod +x ./gradlew
            ./gradlew build
            
